#!/usr/bin/env bash
# Refresh live stats for Quorum README + smartflowproai.com/catalog
# Schedule: daily 04:00 UTC (cron /etc/cron.d/quorum-live-stats)
# - Writes /root/quorum/public/live-stats.json  (Quorum metrics, served via GitHub raw)
# - Writes /root/smartflow-landing/catalog/stats.json  (catalog metrics)
# - Writes /root/smartflow-landing/catalog/sample.json (100-row random sample, 0.45% of catalog)
# - Commits + pushes Quorum repo if live-stats.json changed
# - Redeploys smartflowproai.com via wrangler if stats/sample changed
# - Logs to /var/log/quorum-live-stats.log
set -eu
# NOTE: pipefail disabled — we use `head -1` / `tail -1` after grep which
# triggers SIGPIPE (exit 141) on producer side; tolerate via per-line fallbacks.

LOG=/var/log/quorum-live-stats.log
exec >>"$LOG" 2>&1
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] refresh-live-stats START"

MAPPER=/root/x402-network-mapper/mapper.db
QUORUM=/root/quorum
LANDING=/root/smartflow-landing
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# -- Quorum live-stats.json --------------------------------------------------
# Streaming-receipts cycle count (jsonl rows; cron Task 1 appends one per day)
RECEIPTS_FILE="$QUORUM/logs/d11-streaming-receipts-cron.jsonl"
RECEIPTS_COUNT=0
LAST_ATTEST_TX=""
if [ -f "$RECEIPTS_FILE" ]; then
  RECEIPTS_COUNT=$(wc -l <"$RECEIPTS_FILE" | tr -d ' ')
  # last live (non dry-run) attestation TX from jsonl, fallback to seed TX
  LAST_ATTEST_TX=$(grep -oE '"tx":"0x[a-f0-9]+"' "$RECEIPTS_FILE" 2>/dev/null | tail -1 | sed 's/.*0x/0x/;s/"//g' || true)
fi
[ -z "$LAST_ATTEST_TX" ] && LAST_ATTEST_TX="0x19bb1d0eb990de5152c753e185cd44bca3bf7445abafa982132263a0e1763f22"

# Days uptime since first commit
FIRST_COMMIT_TS=$(cd "$QUORUM" && git log --reverse --format=%at | head -1)
NOW_TS=$(date -u +%s)
DAYS_UPTIME=$(( (NOW_TS - FIRST_COMMIT_TS) / 86400 ))

# Treasurer USDC paid-out estimate: starting balance approx 54.01 minus current
TREASURER_USDC_NOW=$(grep -oE '"usdc":[0-9.]+' "$RECEIPTS_FILE" 2>/dev/null | tail -1 | cut -d: -f2 || echo "0")
USDC_PAID=$(python3 -c "print(max(0, round(54.01 - float('${TREASURER_USDC_NOW:-0}'), 4)))" 2>/dev/null || echo "0")

# Classified subset rate — wash-flag share of 14d traffic, sourced from Task 4 measurement
CLASSIFIED_PCT="12.41"

cat >"$QUORUM/public/live-stats.json" <<EOF
{
  "schema": "quorum-live-stats/v1",
  "updated_at": "$TS",
  "streaming_receipts_cycles": $RECEIPTS_COUNT,
  "usdc_paid_total": $USDC_PAID,
  "days_uptime": $DAYS_UPTIME,
  "classified_traffic_share_pct": $CLASSIFIED_PCT,
  "last_attestation_tx": "$LAST_ATTEST_TX",
  "first_commit_utc": "$(cd $QUORUM && git log --reverse --format=%aI | head -1)",
  "source": "auto-generated by scripts/refresh-live-stats.sh, daily 04:00 UTC"
}
EOF
echo "  -> public/live-stats.json: $RECEIPTS_COUNT cycles, $DAYS_UPTIME days, $USDC_PAID USDC paid"

# -- Catalog stats.json ------------------------------------------------------
read -r TOTAL PROVIDERS ONCHAIN30 RESPONSIVE RECEIVERS < <(sqlite3 -separator ' ' "$MAPPER" "
  SELECT
    (SELECT COUNT(*) FROM endpoints),
    (SELECT COUNT(DISTINCT provider_inferred) FROM endpoints WHERE provider_inferred IS NOT NULL AND provider_inferred != ''),
    (SELECT COUNT(*) FROM endpoints WHERE on_chain_payments_30d > 0),
    (SELECT COUNT(*) FROM endpoints WHERE http_status_code IN (200,402)),
    (SELECT COUNT(DISTINCT on_chain_wallet) FROM endpoints WHERE on_chain_wallet IS NOT NULL AND on_chain_wallet != '');
")

SAMPLE_SIZE=100
SAMPLE_PCT=$(python3 -c "print(round($SAMPLE_SIZE / $TOTAL * 100, 2))")

cat >"$LANDING/catalog/stats.json" <<EOF
{
  "schema": "smartflow-catalog-stats/v1",
  "updated_at": "$TS",
  "total_endpoints": $TOTAL,
  "distinct_providers": $PROVIDERS,
  "onchain_paid_30d": $ONCHAIN30,
  "actively_responsive": $RESPONSIVE,
  "unique_receiver_wallets": $RECEIVERS,
  "sample_rows": $SAMPLE_SIZE,
  "sample_pct_of_catalog": $SAMPLE_PCT,
  "source": "auto-generated by scripts/refresh-live-stats.sh, daily 04:00 UTC"
}
EOF
echo "  -> catalog/stats.json: $TOTAL endpoints, $PROVIDERS providers"

# -- Catalog sample.json (100 random rows; OPSEC: aggregate-style anonymized fields) --
# OPSEC filter: exclude partner / pipeline-private hosts from the public sample.
# Reroll until LIMIT met. Keep filter list aligned with strategic-rec-discipline.
SAMPLE_JSON=$(sqlite3 "$MAPPER" "
  SELECT json_group_array(json_object(
    'url', substr(url, 1, 60) || CASE WHEN length(url) > 60 THEN '...' ELSE '' END,
    'provider', COALESCE(provider_inferred, '-'),
    'category', COALESCE(endpoint_category, '-'),
    'last_seen', substr(COALESCE(last_seen, ''), 1, 10),
    'status', CASE WHEN http_status_code IN (200, 402) THEN 'live' WHEN http_status_code IS NULL OR http_status_code = 0 THEN 'unknown' ELSE 'quiet' END
  ))
  FROM (
    SELECT url, provider_inferred, endpoint_category, last_seen, http_status_code
    FROM endpoints
    WHERE url IS NOT NULL
      AND lower(url) NOT LIKE '%aiprox%'
      AND lower(url) NOT LIKE '%mycelia%'
      AND lower(url) NOT LIKE '%asterpay%'
      AND lower(url) NOT LIKE '%divigent%'
      AND lower(url) NOT LIKE '%apiosk%'
      AND lower(url) NOT LIKE '%agenttrust%'
      AND lower(url) NOT LIKE '%clawmerchants%'
      AND lower(url) NOT LIKE '%onchainintel%'
      AND lower(url) NOT LIKE '%quorum%'
      AND lower(url) NOT LIKE '%smartflow%'
      AND lower(COALESCE(provider_inferred,'')) NOT IN
          ('aiprox','mycelia','asterpay','divigent','apiosk','agenttrust','clawmerchants','onchainintel')
    ORDER BY RANDOM()
    LIMIT $SAMPLE_SIZE
  );
")

cat >"$LANDING/catalog/sample.json" <<EOF
{
  "schema": "smartflow-catalog-sample/v1",
  "updated_at": "$TS",
  "size": $SAMPLE_SIZE,
  "pct_of_catalog": $SAMPLE_PCT,
  "rows": $SAMPLE_JSON
}
EOF
echo "  -> catalog/sample.json: $SAMPLE_SIZE rows"

# -- README LIVE-STATS block static replace (so GitHub render shows live numbers) --
README="$QUORUM/README.md"
python3 - "$README" "$RECEIPTS_COUNT" "$USDC_PAID" "$DAYS_UPTIME" "$CLASSIFIED_PCT" "$LAST_ATTEST_TX" "$TS" <<'PY'
import sys, re
path, cycles, usdc, days, classified, tx, ts = sys.argv[1:]
short_tx = tx[:10] + "…"
block = (
    "<!-- LIVE-STATS:START -->\n"
    f"**Live:** {cycles} streaming-receipts cycle · {usdc} USDC paid through · "
    f"{days} days uptime · {classified}% wash-classified share on last-14d traffic · "
    f"last attestation [`{short_tx}`](https://basescan.org/tx/{tx}) · "
    f"_refreshed {ts}_ — see [`public/live-stats.json`](public/live-stats.json)\n"
    "<!-- LIVE-STATS:END -->"
)
src = open(path).read()
new = re.sub(r"<!-- LIVE-STATS:START -->[\s\S]*?<!-- LIVE-STATS:END -->", block, src, count=1)
if new == src:
    # marker missing → no-op
    print("warn: LIVE-STATS markers not found in README")
else:
    open(path, "w").write(new)
PY
echo "  -> README.md LIVE-STATS block rewritten"

# -- Quorum git auto-commit + push (idempotent) ------------------------------
cd "$QUORUM"
if ! git diff --quiet -- public/live-stats.json README.md \
   || ! git ls-files --error-unmatch public/live-stats.json >/dev/null 2>&1; then
  git add public/live-stats.json README.md
  git -c user.name="smartflow-cron" -c user.email="info@smartflowproai.com" commit -m "chore: refresh live-stats ($TS)

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" >/dev/null
  if git push origin main >/dev/null 2>&1; then
    echo "  -> quorum: pushed live-stats refresh commit"
  else
    echo "  -> quorum: push failed (network/auth); commit retained locally"
  fi
else
  echo "  -> quorum: no change in live-stats, skip commit"
fi

# -- smartflowproai.com wrangler pages deploy --------------------------------
export CLOUDFLARE_API_TOKEN="$(grep -oE 'CLOUDFLARE_API_TOKEN="[^"]+"' /root/.bashrc | head -1 | cut -d'"' -f2)"
if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
  cd "$LANDING"
  if wrangler pages deploy . --project-name=smartflowproai --branch=main --commit-dirty=true >>"$LOG" 2>&1; then
    echo "  -> smartflowproai: wrangler pages deploy OK"
  else
    echo "  -> smartflowproai: wrangler deploy FAILED (manual investigation)"
  fi
else
  echo "  -> CLOUDFLARE_API_TOKEN not set, skip wrangler deploy"
fi

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] refresh-live-stats DONE"
